name: Node.js CI and Deploy

on:
    push:
        branches: ['dev', 'master']
    pull_request:
        branches: ['dev', 'master']

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x] # Adjust as needed

        steps:
            - uses: actions/checkout@v2

            - name: Install sshpass
              run: sudo apt-get update && sudo apt-get install -y sshpass

            - name: Checkout and pull changes from the dev branch
              if: github.ref == 'refs/heads/dev'
              run: |
                  sshpass -p 'TA4bgvMmMokqrKLOM1je' ssh -o StrictHostKeyChecking=no root@146.190.56.16 'cd /var/swiftsales-api && sudo git pull'

            - name: Composer install
              if: github.ref == 'refs/heads/dev'
              run: |
                  sshpass -p 'TA4bgvMmMokqrKLOM1je' ssh -o StrictHostKeyChecking=no root@146.190.56.16 'cd /var/swiftsales-api && sudo composer install'

            - name: Migrate and seed
              if: github.ref == 'refs/heads/dev'
              run: |
                  sshpass -p 'TA4bgvMmMokqrKLOM1je' ssh -o StrictHostKeyChecking=no root@146.190.56.16 'cd /var/swiftsales-api && sudo bash initialize_local_db.sh'

            